# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b360418dfec1fe0567dfeb41c020cd30226751c1bb154aea803393d1003eba235385fda895ca5715b108ffe1316a3c0cc16b182ed63b2e742ecb7557f86b045a

test:
  secret_key_base: baa63bd2c7aeed4b9bc3c7fd5ccf3212804666e036ecdd8a3aedce49e43b59d3de80aa74009d69e1afc0cbb4055317114cbcf46d67ac132646de5c1b78aafd43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
